name: Publish package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release
      - name: Test
        run: dotnet test --no-build --configuration Release
      - name: Publish
        run: |
          cp .\README.md .\EscPosSharp\
          dotnet pack --no-build --configuration Release --output nupkgs
          dotnet nuget push .\nupkgs\*.nupkg --skip-duplicate --no-symbols true
